import type { Resource, Badge, Course, Tag, ColorVariant, SiteSettings } from './types'

// Site settings - initial values
export const initialSiteSettings: SiteSettings = {
  title: 'CAREER',
  description: 'Browse and manage career resources, events, and learning materials',
}

// Color variants - the managed palette for tags
export const initialColorVariants: ColorVariant[] = [
  { id: 'cv-1', name: 'Navy', background: '#3D5B78', text: '#FFFFFF' },
  { id: 'cv-2', name: 'Steel', background: '#8192A6', text: '#FFFFFF' },
  { id: 'cv-3', name: 'Slate', background: '#E2E8F0', text: '#475569', borderColor: '#CBD5E1' },
  { id: 'cv-4', name: 'Teal', background: '#0D9488', text: '#FFFFFF' },
  { id: 'cv-5', name: 'Amber', background: '#D97706', text: '#FFFFFF' },
]

export const badges: Badge[] = [
  { id: 'badge-1', name: 'Beginner', color: '#22c55e' },
  { id: 'badge-2', name: 'Intermediate', color: '#f59e0b' },
  { id: 'badge-3', name: 'Advanced', color: '#ef4444' },
  { id: 'badge-4', name: 'Certified', color: '#3b82f6' },
  { id: 'badge-5', name: 'Expert', color: '#8b5cf6' },
]

export const courses: Course[] = [
  { id: 'course-1', name: 'Introduction to Web Development', code: 'WEB101' },
  { id: 'course-2', name: 'Advanced JavaScript', code: 'JS201' },
  { id: 'course-3', name: 'Data Science Fundamentals', code: 'DS101' },
  { id: 'course-4', name: 'UX Design Principles', code: 'UX101' },
  { id: 'course-5', name: 'Cloud Architecture', code: 'CLOUD301' },
]

export const initialTags: Tag[] = [
  { id: 'tag-1', name: 'Tutorial', colorVariantId: 'cv-1' },
  { id: 'tag-2', name: 'Reference', colorVariantId: 'cv-2' },
  { id: 'tag-3', name: 'Workshop', colorVariantId: 'cv-1' },
  { id: 'tag-4', name: 'Webinar', colorVariantId: 'cv-5' },
  { id: 'tag-5', name: 'Documentation', colorVariantId: 'cv-3' },
  { id: 'tag-6', name: 'Case Study', colorVariantId: 'cv-4' },
  { id: 'tag-7', name: 'Best Practices', colorVariantId: 'cv-4' },
  { id: 'tag-8', name: 'Getting Started', colorVariantId: 'cv-1' },
  { id: 'tag-9', name: 'Deep Dive', colorVariantId: 'cv-5' },
  { id: 'tag-10', name: 'Industry', colorVariantId: 'cv-2' },
]

const now = new Date()
const addDays = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000)
const subDays = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000)

export const initialResources: Resource[] = [
  {
    id: 'res-1',
    title: 'Getting Started with React',
    description: 'A comprehensive guide to building your first React application. Learn the fundamentals including components, state, and props.',
    type: 'document',
    fileUrl: '/files/react-guide.pdf',
    tags: ['tag-1', 'tag-8'],
    linkedBadgeIds: ['badge-1'],
    linkedCourseIds: ['course-1'],
    isStarred: true,
    createdAt: subDays(30),
    updatedAt: subDays(5),
  },
  {
    id: 'res-2',
    title: 'JavaScript Best Practices 2024',
    description: 'Learn modern JavaScript patterns and practices that will make your code cleaner, more maintainable, and performant.',
    type: 'video',
    url: 'https://example.com/js-best-practices',
    tags: ['tag-7', 'tag-2'],
    linkedBadgeIds: ['badge-2', 'badge-4'],
    linkedCourseIds: ['course-2'],
    isStarred: true,
    createdAt: subDays(20),
    updatedAt: subDays(2),
  },
  {
    id: 'res-3',
    title: 'Web Development Workshop',
    description: 'Join us for an interactive hands-on workshop covering modern web development techniques including responsive design and accessibility.',
    type: 'event',
    tags: ['tag-3'],
    linkedBadgeIds: ['badge-1', 'badge-2'],
    linkedCourseIds: ['course-1'],
    isStarred: false,
    createdAt: subDays(10),
    updatedAt: subDays(1),
    startDate: addDays(7),
    endDate: addDays(7),
  },
  {
    id: 'res-4',
    title: 'Data Visualization Techniques',
    description: 'Explore various methods for presenting data effectively using charts, graphs, and interactive visualizations.',
    type: 'link',
    url: 'https://example.com/data-viz',
    tags: ['tag-2', 'tag-9'],
    linkedBadgeIds: ['badge-3'],
    linkedCourseIds: ['course-3'],
    isStarred: false,
    createdAt: subDays(15),
    updatedAt: subDays(15),
  },
  {
    id: 'res-5',
    title: 'UX Research Methods Webinar',
    description: 'A live webinar discussing user research methodologies including interviews, surveys, and usability testing.',
    type: 'event',
    tags: ['tag-4'],
    linkedBadgeIds: ['badge-2'],
    linkedCourseIds: ['course-4'],
    isStarred: true,
    createdAt: subDays(5),
    updatedAt: subDays(1),
    startDate: addDays(3),
    endDate: addDays(3),
  },
  {
    id: 'res-6',
    title: 'Cloud Infrastructure Diagram',
    description: 'Reference architecture diagram showing best practices for cloud infrastructure setup with microservices.',
    type: 'image',
    fileUrl: '/files/cloud-arch.png',
    tags: ['tag-2', 'tag-7'],
    linkedBadgeIds: ['badge-3', 'badge-5'],
    linkedCourseIds: ['course-5'],
    isStarred: false,
    createdAt: subDays(25),
    updatedAt: subDays(10),
  },
  {
    id: 'res-7',
    title: 'Podcast: Future of Frontend',
    description: 'An engaging discussion about emerging trends in frontend development including AI-assisted coding and new frameworks.',
    type: 'audio',
    url: 'https://example.com/podcast-frontend',
    tags: ['tag-10'],
    linkedBadgeIds: [],
    linkedCourseIds: ['course-1', 'course-2'],
    isStarred: false,
    createdAt: subDays(8),
    updatedAt: subDays(8),
  },
  {
    id: 'res-8',
    title: 'TypeScript Deep Dive',
    description: 'An in-depth exploration of TypeScript features including generics, decorators, and advanced type manipulation.',
    type: 'document',
    fileUrl: '/files/typescript-deep.pdf',
    tags: ['tag-9', 'tag-5'],
    linkedBadgeIds: ['badge-3'],
    linkedCourseIds: ['course-2'],
    isStarred: false,
    createdAt: subDays(40),
    updatedAt: subDays(12),
  },
  {
    id: 'res-9',
    title: 'Annual Tech Conference 2024',
    description: 'Our flagship annual conference featuring keynotes, workshops, and networking opportunities with industry leaders.',
    type: 'event',
    tags: ['tag-3', 'tag-10'],
    linkedBadgeIds: ['badge-4', 'badge-5'],
    linkedCourseIds: ['course-1', 'course-2', 'course-3'],
    isStarred: true,
    createdAt: subDays(60),
    updatedAt: subDays(3),
    startDate: addDays(14),
    endDate: addDays(16),
  },
  {
    id: 'res-10',
    title: 'API Design Guidelines',
    description: 'Comprehensive documentation covering RESTful API design patterns, versioning strategies, and error handling.',
    type: 'link',
    url: 'https://example.com/api-guidelines',
    tags: ['tag-5', 'tag-7'],
    linkedBadgeIds: ['badge-2', 'badge-3'],
    linkedCourseIds: ['course-5'],
    isStarred: false,
    createdAt: subDays(35),
    updatedAt: subDays(20),
  },
  {
    id: 'res-11',
    title: 'Machine Learning Basics',
    description: 'An introductory video series explaining fundamental machine learning concepts and algorithms.',
    type: 'video',
    url: 'https://example.com/ml-basics',
    tags: ['tag-1', 'tag-8'],
    linkedBadgeIds: ['badge-1'],
    linkedCourseIds: ['course-3'],
    isStarred: false,
    createdAt: subDays(22),
    updatedAt: subDays(22),
  },
  {
    id: 'res-12',
    title: 'Design System Components',
    description: 'A visual library showcasing all available UI components with usage examples and accessibility notes.',
    type: 'image',
    fileUrl: '/files/design-system.png',
    tags: ['tag-2', 'tag-5'],
    linkedBadgeIds: [],
    linkedCourseIds: ['course-4'],
    isStarred: false,
    createdAt: subDays(18),
    updatedAt: subDays(5),
  },
  {
    id: 'res-13',
    title: 'Case Study: E-commerce Redesign',
    description: 'Detailed analysis of a successful e-commerce platform redesign including metrics and user feedback.',
    type: 'document',
    fileUrl: '/files/ecommerce-case.pdf',
    tags: ['tag-6'],
    linkedBadgeIds: ['badge-4'],
    linkedCourseIds: ['course-4'],
    isStarred: false,
    createdAt: subDays(28),
    updatedAt: subDays(28),
  },
  {
    id: 'res-14',
    title: 'Monthly Office Hours',
    description: 'Regular Q&A session where you can get your questions answered by our expert instructors.',
    type: 'event',
    tags: ['tag-4'],
    linkedBadgeIds: [],
    linkedCourseIds: [],
    isStarred: false,
    createdAt: subDays(2),
    updatedAt: subDays(2),
    startDate: addDays(1),
    endDate: addDays(1),
  },
  {
    id: 'res-15',
    title: 'Security Best Practices',
    description: 'Essential security guidelines for web applications covering authentication, authorization, and data protection.',
    type: 'document',
    fileUrl: '/files/security-guide.pdf',
    tags: ['tag-7', 'tag-5'],
    linkedBadgeIds: ['badge-3', 'badge-5'],
    linkedCourseIds: ['course-5'],
    isStarred: true,
    createdAt: subDays(45),
    updatedAt: subDays(7),
  },
  {
    id: 'res-16',
    title: 'Accessibility Audit Checklist',
    description: 'A comprehensive checklist for ensuring your web applications meet WCAG 2.1 accessibility standards.',
    type: 'link',
    url: 'https://example.com/a11y-checklist',
    tags: ['tag-2', 'tag-7'],
    linkedBadgeIds: ['badge-4'],
    linkedCourseIds: ['course-1', 'course-4'],
    isStarred: false,
    createdAt: subDays(33),
    updatedAt: subDays(15),
  },
  {
    id: 'res-17',
    title: 'Interview: Industry Expert',
    description: 'Podcast interview with a leading industry expert discussing career growth and technology trends.',
    type: 'audio',
    url: 'https://example.com/expert-interview',
    tags: ['tag-10'],
    linkedBadgeIds: ['badge-5'],
    linkedCourseIds: [],
    isStarred: false,
    createdAt: subDays(12),
    updatedAt: subDays(12),
  },
  {
    id: 'res-18',
    title: 'React Performance Workshop',
    description: 'Hands-on workshop focusing on optimizing React application performance using profiling tools and best practices.',
    type: 'event',
    tags: ['tag-3', 'tag-9'],
    linkedBadgeIds: ['badge-2', 'badge-3'],
    linkedCourseIds: ['course-2'],
    isStarred: false,
    createdAt: subDays(7),
    updatedAt: subDays(1),
    startDate: addDays(21),
    endDate: addDays(21),
  },
  {
    id: 'res-19',
    title: 'Database Schema Design',
    description: 'Learn how to design efficient and scalable database schemas for modern applications.',
    type: 'video',
    url: 'https://example.com/db-design',
    tags: ['tag-1', 'tag-2'],
    linkedBadgeIds: ['badge-2'],
    linkedCourseIds: ['course-3', 'course-5'],
    isStarred: false,
    createdAt: subDays(50),
    updatedAt: subDays(30),
  },
  {
    id: 'res-20',
    title: 'Wireframe Templates',
    description: 'Collection of wireframe templates for common web and mobile application patterns.',
    type: 'image',
    fileUrl: '/files/wireframes.png',
    tags: ['tag-2'],
    linkedBadgeIds: ['badge-1'],
    linkedCourseIds: ['course-4'],
    isStarred: false,
    createdAt: subDays(38),
    updatedAt: subDays(38),
  },
  {
    id: 'res-21',
    title: 'Certification Exam Prep',
    description: 'Study materials and practice questions to help you prepare for professional certification exams.',
    type: 'document',
    fileUrl: '/files/cert-prep.pdf',
    tags: ['tag-2', 'tag-8'],
    linkedBadgeIds: ['badge-4'],
    linkedCourseIds: ['course-1', 'course-2', 'course-3'],
    isStarred: false,
    createdAt: subDays(55),
    updatedAt: subDays(10),
  },
  {
    id: 'res-22',
    title: 'Kubernetes Workshop',
    description: 'Beginner-friendly workshop on container orchestration with Kubernetes including hands-on exercises.',
    type: 'event',
    tags: ['tag-3', 'tag-8'],
    linkedBadgeIds: ['badge-1', 'badge-2'],
    linkedCourseIds: ['course-5'],
    isStarred: false,
    createdAt: subDays(4),
    updatedAt: subDays(1),
    startDate: addDays(28),
    endDate: addDays(28),
  },
  {
    id: 'res-23',
    title: 'CSS Grid Masterclass',
    description: 'Complete video course covering CSS Grid layout from basics to advanced responsive design patterns.',
    type: 'video',
    url: 'https://example.com/css-grid',
    tags: ['tag-1', 'tag-9'],
    linkedBadgeIds: ['badge-2', 'badge-3'],
    linkedCourseIds: ['course-1'],
    isStarred: false,
    createdAt: subDays(42),
    updatedAt: subDays(25),
  },
  {
    id: 'res-24',
    title: 'Startup Case Study: Growth',
    description: 'Analysis of a startup rapid growth phase including technical scaling challenges and solutions.',
    type: 'document',
    fileUrl: '/files/startup-growth.pdf',
    tags: ['tag-6', 'tag-10'],
    linkedBadgeIds: ['badge-5'],
    linkedCourseIds: ['course-5'],
    isStarred: false,
    createdAt: subDays(65),
    updatedAt: subDays(40),
  },
  {
    id: 'res-25',
    title: 'GraphQL vs REST Discussion',
    description: 'Recorded panel discussion comparing GraphQL and REST APIs with real-world use cases.',
    type: 'audio',
    url: 'https://example.com/graphql-rest',
    tags: ['tag-10', 'tag-9'],
    linkedBadgeIds: ['badge-3'],
    linkedCourseIds: ['course-2', 'course-5'],
    isStarred: false,
    createdAt: subDays(16),
    updatedAt: subDays(16),
  },
  // Additional featured resources for carousel overflow
  {
    id: 'res-26',
    title: 'Building Scalable APIs',
    description: 'Learn architectural patterns for building APIs that can handle millions of requests.',
    type: 'video',
    url: 'https://example.com/scalable-apis',
    tags: ['tag-1', 'tag-7'],
    linkedBadgeIds: ['badge-3', 'badge-5'],
    linkedCourseIds: ['course-5'],
    isStarred: true,
    createdAt: subDays(8),
    updatedAt: subDays(1),
  },
  {
    id: 'res-27',
    title: 'Mobile App Development Guide',
    description: 'Comprehensive guide to building cross-platform mobile applications with React Native.',
    type: 'document',
    fileUrl: '/files/mobile-guide.pdf',
    tags: ['tag-1', 'tag-8'],
    linkedBadgeIds: ['badge-1', 'badge-2'],
    linkedCourseIds: ['course-1'],
    isStarred: true,
    createdAt: subDays(12),
    updatedAt: subDays(3),
  },
  {
    id: 'res-28',
    title: 'DevOps Pipeline Setup',
    description: 'Step-by-step tutorial for setting up CI/CD pipelines with GitHub Actions and automated testing.',
    type: 'video',
    url: 'https://example.com/devops-pipeline',
    tags: ['tag-1', 'tag-7'],
    linkedBadgeIds: ['badge-2', 'badge-3'],
    linkedCourseIds: ['course-5'],
    isStarred: true,
    createdAt: subDays(6),
    updatedAt: subDays(2),
  },
  {
    id: 'res-29',
    title: 'AI Integration Workshop',
    description: 'Hands-on workshop on integrating AI capabilities into your web applications using modern APIs.',
    type: 'event',
    tags: ['tag-3', 'tag-9'],
    linkedBadgeIds: ['badge-3', 'badge-5'],
    linkedCourseIds: ['course-3'],
    isStarred: true,
    createdAt: subDays(3),
    updatedAt: subDays(1),
    startDate: addDays(10),
    endDate: addDays(10),
  },
  {
    id: 'res-30',
    title: 'Product Management Essentials',
    description: 'Essential skills and frameworks for product managers in technology companies.',
    type: 'document',
    fileUrl: '/files/pm-essentials.pdf',
    tags: ['tag-2', 'tag-8'],
    linkedBadgeIds: ['badge-2'],
    linkedCourseIds: ['course-4'],
    isStarred: true,
    createdAt: subDays(14),
    updatedAt: subDays(5),
  },
  {
    id: 'res-31',
    title: 'Microservices Architecture Patterns',
    description: 'Deep dive into microservices design patterns and best practices for distributed systems.',
    type: 'link',
    url: 'https://example.com/microservices',
    tags: ['tag-9', 'tag-7'],
    linkedBadgeIds: ['badge-3', 'badge-5'],
    linkedCourseIds: ['course-5'],
    isStarred: true,
    createdAt: subDays(9),
    updatedAt: subDays(4),
  },
  {
    id: 'res-32',
    title: 'Frontend Testing Strategies',
    description: 'Comprehensive overview of testing strategies including unit, integration, and e2e testing.',
    type: 'video',
    url: 'https://example.com/frontend-testing',
    tags: ['tag-1', 'tag-7'],
    linkedBadgeIds: ['badge-2', 'badge-4'],
    linkedCourseIds: ['course-2'],
    isStarred: true,
    createdAt: subDays(11),
    updatedAt: subDays(2),
  },
  // More resources for category variety
  {
    id: 'res-33',
    title: 'User Interview Techniques',
    description: 'Learn effective techniques for conducting user interviews and synthesizing insights.',
    type: 'document',
    fileUrl: '/files/user-interviews.pdf',
    tags: ['tag-6', 'tag-2'],
    linkedBadgeIds: ['badge-2'],
    linkedCourseIds: ['course-4'],
    isStarred: false,
    createdAt: subDays(20),
    updatedAt: subDays(15),
  },
  {
    id: 'res-34',
    title: 'Design Thinking Workshop',
    description: 'Interactive workshop introducing design thinking methodology for problem solving.',
    type: 'event',
    tags: ['tag-3', 'tag-6'],
    linkedBadgeIds: ['badge-1'],
    linkedCourseIds: ['course-4'],
    isStarred: false,
    createdAt: subDays(5),
    updatedAt: subDays(2),
    startDate: addDays(18),
    endDate: addDays(18),
  },
  {
    id: 'res-35',
    title: 'SQL Performance Optimization',
    description: 'Advanced techniques for optimizing SQL queries and database performance.',
    type: 'video',
    url: 'https://example.com/sql-optimization',
    tags: ['tag-9', 'tag-2'],
    linkedBadgeIds: ['badge-3'],
    linkedCourseIds: ['course-3'],
    isStarred: false,
    createdAt: subDays(25),
    updatedAt: subDays(20),
  },
  {
    id: 'res-36',
    title: 'Remote Team Collaboration',
    description: 'Best practices for effective collaboration in distributed and remote teams.',
    type: 'link',
    url: 'https://example.com/remote-teams',
    tags: ['tag-7', 'tag-10'],
    linkedBadgeIds: [],
    linkedCourseIds: [],
    isStarred: false,
    createdAt: subDays(18),
    updatedAt: subDays(18),
  },
  {
    id: 'res-37',
    title: 'Agile Sprint Planning',
    description: 'Guide to effective sprint planning and estimation techniques for agile teams.',
    type: 'document',
    fileUrl: '/files/sprint-planning.pdf',
    tags: ['tag-5', 'tag-7'],
    linkedBadgeIds: ['badge-2'],
    linkedCourseIds: [],
    isStarred: false,
    createdAt: subDays(30),
    updatedAt: subDays(25),
  },
  {
    id: 'res-38',
    title: 'Startup Pitch Workshop',
    description: 'Learn how to create and deliver compelling pitches for your startup ideas.',
    type: 'event',
    tags: ['tag-3', 'tag-10'],
    linkedBadgeIds: ['badge-1', 'badge-2'],
    linkedCourseIds: [],
    isStarred: false,
    createdAt: subDays(7),
    updatedAt: subDays(3),
    startDate: addDays(25),
    endDate: addDays(25),
  },
  {
    id: 'res-39',
    title: 'Data Privacy Compliance',
    description: 'Understanding GDPR, CCPA, and other data privacy regulations for developers.',
    type: 'document',
    fileUrl: '/files/privacy-compliance.pdf',
    tags: ['tag-5', 'tag-7'],
    linkedBadgeIds: ['badge-4'],
    linkedCourseIds: ['course-5'],
    isStarred: false,
    createdAt: subDays(35),
    updatedAt: subDays(30),
  },
  {
    id: 'res-40',
    title: 'Tech Leadership Webinar',
    description: 'Insights from tech leaders on building and managing high-performing engineering teams.',
    type: 'event',
    tags: ['tag-4', 'tag-10'],
    linkedBadgeIds: ['badge-5'],
    linkedCourseIds: [],
    isStarred: false,
    createdAt: subDays(4),
    updatedAt: subDays(1),
    startDate: addDays(5),
    endDate: addDays(5),
  },
]
